# Generated by Django 2.2.2 on 2019-10-21 16:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=3000, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=3000, verbose_name='Last Name')),
                ('email', models.EmailField(default='', max_length=3000, verbose_name='Email')),
                ('gender', models.CharField(default='', max_length=3000, verbose_name='Gender')),
                ('address', models.CharField(default='', max_length=3000, verbose_name='Address')),
                ('city', models.CharField(default='', max_length=3000, verbose_name='City')),
                ('uid', models.CharField(default='', max_length=3000, verbose_name='User ID#')),
                ('date', models.CharField(default='', max_length=3000, verbose_name='Date')),
                ('time', models.CharField(default='', max_length=3000, verbose_name='Timestamp')),
                ('referral', models.CharField(default='', max_length=3000, verbose_name='Referral')),
                ('phone_number', models.CharField(default='', max_length=10, verbose_name='Main Phone Number')),
                ('purpose', models.CharField(default='', max_length=3000, verbose_name='Purpose')),
                ('household_number', models.CharField(default='', max_length=3000, verbose_name='Number of People in Household')),
                ('household_income', models.CharField(default='', max_length=3000, verbose_name='Household Income')),
                ('race', models.CharField(default='', max_length=3000, verbose_name='Ethnicity')),
                ('dob', models.CharField(default='', max_length=3000, verbose_name='Date of Birth')),
                ('veteran', models.CharField(default='', max_length=3000, verbose_name='Veteran Status')),
                ('disabled', models.CharField(default='', max_length=3000, verbose_name='Disabled Status')),
                ('marital_status', models.CharField(default='', max_length=3000, verbose_name='Marital Status')),
                ('major_purpose', models.CharField(default='', max_length=3000, verbose_name='Major Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=3000, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=3000, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=3000, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Main Phone Number')),
                ('address', models.CharField(max_length=3000, verbose_name='Address')),
                ('city', models.CharField(max_length=3000, verbose_name='City')),
                ('referral', models.CharField(blank=True, choices=[('Friend', 'Friend'), ('Online Advertisement', 'Online Advertisement'), ('Other', 'Other')], max_length=3000, verbose_name='How did you hear about our services?')),
                ('purpose1', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Job Placement Assistance', 'Job Placement Assistance'), ('Resume Preparation', 'Resume Preparation'), ('Mock Interviewing', 'Mock Interviewing'), ('Career Counseling', 'Career Counseling')], default='None', max_length=79, verbose_name='<strong>Employment Programs</strong>')),
                ('purpose2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Construction', 'Construction'), ('Pre-Apprenticeship', 'Pre-Apprenticeship'), ('Microsoft Office Certification', 'Microsoft Office Certification'), ('A+ certification', 'A+ certification'), ('paintWorks', 'paintWorks')], default='None', max_length=90, verbose_name='<strong>Workforce Training Programs</strong>')),
                ('purpose3', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Public Income Benefits Screening', 'Public Income Benefits Screening'), ('Financial Workshop', 'Financial Workshop'), ('Financial Coaching', 'Financial Coaching ')], default='None', max_length=70, verbose_name='<strong>Financial Opportunity Center</strong>')),
                ('purpose4', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Start Saving on a Shoestring', 'Start Saving on a Shoestring'), ('Early Career Guide to Becoming Financially Fit', 'Early Career Guide to Becoming Financially Fit'), ('MoneyWISE is a Family Affair)', 'MoneyWISE is a Family Affair'), ('Managing Credit and Debt - The RIGHT Way', 'Managing Credit and Debt - The RIGHT Way'), ('Protecting Your Assets; Protecting Your Family', 'Protecting Your Assets; Protecting Your Family')], default='None', max_length=193, verbose_name='<strong>Workshops</strong>')),
                ('purpose5', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Rental Assistance / Counseling', 'Rental Assistance / Counseling'), ('First Time Homebuyer Counseling', 'First Time Homebuyer Counseling'), ('Foreclosure Counseling', 'Foreclosure Counseling'), ('Post Purchase Counseling', 'Post Purchase Counseling')], default='None', max_length=110, verbose_name='<strong>Housing</strong>')),
                ('purpose6', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('High School Equivalency Program', 'High School Equivalency Program'), ('Job Readiness', 'Job Readiness'), ('Career Preparation', 'Career Preparation')], default='None', max_length=64, verbose_name='<strong>Young Adults Program</strong>')),
                ('purpose7', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Early Childhood Center', 'Early Childhood Center'), ('Newark Kids Code', 'Newark Kids Code')], default='None', max_length=39, verbose_name='<strong>Youth Education</strong>')),
                ('purpose8', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Youth Programs', 'Youth Programs'), ('Adult Programs', 'Adult Programs'), ('Early Childhood', 'Early Childhood')], default='None', max_length=45, verbose_name='<strong>Volunteering</strong>')),
                ('major_purpose', models.CharField(default='None', max_length=264, verbose_name='Major Purpose')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, verbose_name='Gender')),
                ('household_number', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5 or above', '5 or above')], default='0', max_length=3000, verbose_name='Number of People in Household')),
                ('dob', models.CharField(help_text='Please provide in the following format: MM/DD/YYY', max_length=10, verbose_name='Date of Birth')),
                ('race', models.CharField(choices=[('White', 'White'), ('Black/Afro America', 'Black/Afro American'), ('Hispanic', 'Hispanic'), ('Asian', 'Asian'), ('Mixed', 'Mixed'), ('Other', 'Other')], default='None', max_length=3000, verbose_name='Ethnicity')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Married', 'Married')], max_length=3000, verbose_name='Matrial Status')),
                ('household_income', models.CharField(choices=[('under $25,000', 'under $25,000'), ('$25,000 - $35,000', '$25,000 - $35,000'), ('$36,000 - $46,000', '$36,000 - $46,000'), ('$47,000 - $57,000', '$46,000 - $57,000'), ('$58,000 - $68,000', '$58,000 - $68,000'), ('$69,000 - $79,000', '$69,000 - $79,000'), ('$80,000 - $90,000', '$80,000 - $90,000'), ('over $90,000', 'over $90,000')], max_length=100, verbose_name='Household Income')),
                ('veteran', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Are you a Veteran?')),
                ('disabled', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, verbose_name='Are you Disabled?')),
            ],
        ),
    ]
