# Generated by Django 2.2.2 on 2020-01-11 13:13

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20191029_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='purpose9',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Food Referral', 'Food Referral'), ('Computer Lab', 'Computer Lab'), ('Make Copies', 'Make Copies'), ('Other', 'Other')], default='None', max_length=44, verbose_name='<strong>Other</strong>'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Job Placement Assistance', 'Job Placement Assistance'), ('Resume Preparation', 'Resume Preparation'), ('Mock Interviewing', 'Mock Interviewing'), ('Career Counseling', 'Career Counseling')], default='None', max_length=79, verbose_name='<strong>Employment Assistance</strong>'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Construction', 'Construction'), ('Pre-Apprenticeship', 'Pre-Apprenticeship'), ('Microsoft Office Certification', 'Microsoft Office Certification'), ('A+ certification', 'A+ certification'), ('paintWorks', 'paintWorks')], default='None', max_length=90, verbose_name='<strong>Training Programs</strong>'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Public Income Benefits Screening', 'Public Income Benefits Screening'), ('Financial Workshop', 'Financial Workshop'), ('Financial Coaching', 'Financial Coaching ')], default='None', max_length=70, verbose_name='<strong>Financial Information</strong>'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Rental Assistance / Counseling', 'Rental Assistance / Counseling'), ('First Time Homebuyer Counseling', 'First Time Homebuyer Counseling'), ('Foreclosure Counseling', 'Foreclosure Counseling'), ('Post Purchase Counseling', 'Post Purchase Counseling')], default='None', max_length=110, verbose_name='<strong>Housing or Rental Assistance</strong>'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='purpose6',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('High School Equivalency Program', 'High School Equivalency Program'), ('Job Readiness', 'Job Readiness'), ('Career Preparation', 'Career Preparation')], default='None', max_length=64, verbose_name='<strong>Young Adult Programs / Youth Programs</strong>'),
        ),
    ]
